### PR TITLE
Added a link to a step guide for making a pull request.

### PR DESCRIPTION
**Pull request by khalibartan**
This should give learners enough materials to learn form.

### CODE REVIEW

**Comment by pbaisla** [comment]
Nice work @khalibartan :+1: but you should make your commit messages more descriptive. See [this](http://chris.beams.io/posts/git-commit/).

Try changing your last commit message with `git commit --amend`. I'll accept the PR once you have done that.

**Comment by khalibartan** [comment]
How can we write a long commit message with a short description.
Can you tell me commands for it?

**Comment by pbaisla** [comment]
You can do that with just `git commit`. This will open up an editor for you to write your commit message. On the first line write a short description for your commit. Leave the second line blank and from the third line you can write a longer description of your commit.

**Comment by pbaisla** [comment]
BTW do you want to add anything else to this PR or should I accept it?

**Comment by khalibartan** [comment]
okay

**Comment by khalibartan** [comment]
Nope this was as much I wanted to add.

**Pull request merged**
