### PR TITLE
Created a platform for discussion

### PR DESCRIPTION
**Pull request by khalibartan**
@pbaisla  Seeing only 3 names in the list I felt people needed a platform to ask
there doubts reagrading open source. Didn't liked facebook as platform
for this so created one myself.Also made list in alphabetic order. check issue #5

### CODE REVIEW

**Comment by UtpalKumarJha** [comment]
I don't think open Discussions on slack would be a good idea . The Idea behind Slack is to get project team members involved in a discussion where in almost everyone actively participates . So most of the times many people would just receive bunch of emails from Slack . I am not still sure how right I am . But if you do want to make a team you would have to send bunch of invitations by yourself . Comment from @pbaisla  @aayushnul @zarinn3pal  or basically any other person who has used slack actively would be appreciated .

**Comment by pbaisla** [comment]
I agree with @coolutpal . Also slack isn't a very open medium of communication. We had previously considered using IRC for that purpose since most open source organizations use it but we didn't think people would actively participate. If you feel that we really do need a separate platform for this then we could set up a local IRC server on the LAN.

**Comment by khalibartan** [comment]
@pbaisla I agree that slack is not that much of a open platform we can use it later if some we find some highly interested people. I think we do need a local platform and encourage people participation in it. Facebook is not a good medium for asking doubts. We can also use this IRC server for more general purpose related to programming club too.

**Comment by UtpalKumarJha** [comment]
We are thinking of creating local IRC channel not now of course but in the near future . So if you just remove the slack part in your pull request it would be great .

**Pull request closed without merging**
