### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by npcoder2k14**

### CODE REVIEW

**Comment by pbaisla** [comment]
Good work! :+1: But please keep the names in alphabetical order. You can commit again with the changes and they will be automatically added to this PR (pull request). 

Or, you can modify the current commit by using `git commit --amend` instead. You can also improve the commit message this way to make it more meaningful. See [this](http://chris.beams.io/posts/git-commit/) for more on commit messages.

I will merge this PR once you have done that.

**Comment by pbaisla** [comment]
@npcoder2k14 Thanks for making it in alphabetical order! 

Would you like to try squashing your commits into a single commit? If yes, I'll tell you how to do it and if not, let me know and I'll merge the PR as it is.

**Comment by npcoder2k14** [comment]
sure sir ...I would love to learn it

**Comment by pbaisla** [comment]
Great! Please follow [this](http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) for instructions. If you run into any problems, don't hesistate to ask for help.

**Comment by pbaisla** [comment]
@npcoder2k14 Are you working on this? It's okay if you're not. I can merge the PR as it is.

**Pull request merged**
